# Generated by Django 5.2.3 on 2025-09-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(verbose_name='')),
                ('name_ru', models.CharField(verbose_name=100)),
                ('name_ua', models.CharField(verbose_name=100)),
                ('name_en', models.CharField(verbose_name=100)),
            ],
        ),
    ]
