# Generated by Django 5.2.3 on 2025-09-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(verbose_name=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
