# Generated by Django 5.2.7 on 2025-10-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
